% addpath(genpath([pwd filesep 'gptoolbox']))
addpath(genpath([pwd filesep 'optimizer']))
addpath(genpath([pwd filesep 'meshes']))
addpath(genpath([pwd filesep 'example_code']))
addpath(genpath([pwd filesep 'external_libraries']))